[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[terminal.shell]
program = "/bin/fish"

[window]
startup_mode = "Maximized"
decorations = "None"

[font]
size = 12.0
offset.x = 0
offset.y = -3

[font.normal]
family = "Monaco"
style = "Regular"

